# Generated by Django 3.0.8 on 2021-05-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75, null=True)),
                ('contacts', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_For_Quotation', models.CharField(max_length=18)),
                ('product', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=65)),
                ('period', models.PositiveIntegerField(default='Days')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='system.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zimra', models.FileField(upload_to='uploads/')),
                ('praz', models.FileField(upload_to='uploads/')),
                ('quotation', models.FileField(default='quotation', upload_to='uploads')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('zimra_date', models.CharField(default='invalid', max_length=20)),
                ('praz_date', models.CharField(default='invalid', max_length=10)),
                ('doc_validity', models.CharField(default='Invalid documents', max_length=22)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='system.Jobs')),
                ('suppliers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
