# Generated by Django 3.0.8 on 2021-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='praz',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='zimra',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Request_For_Quotation',
            field=models.CharField(max_length=50),
        ),
    ]
