# Generated by Django 3.0.8 on 2021-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210509_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Request_For_Quotation',
            field=models.CharField(max_length=150),
        ),
    ]
